[Xdebug]
; Mode to run xdebug with
; - "debug" enables step debugging
; - "develop" enables development helpers including the overloaded var_dump()
; More info: https://xdebug.org/docs/all_settings
xdebug.mode=debug,develop
; What is the host of the client
; If running with docker, use this internal host
xdebug.client_host=host.docker.internal
xdebug.client_port=9000