name: 'Health Check'

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      - name: "Setup PHP v8.3 & Composer v2"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
      - name: "Install dependencies"
        run: |
          yarn --frozen-lockfile
          composer install -o
      - name: "Lint"
        run: |
          yarn lint
          composer lint